### ISSUE TITLE
List semesters on the member page and show status of the courses the user signed up for 

### ISSUE THREAD

**Issue by mariusGundersen** [bardarswingclub/MemberService#67]
Show if the user was approved or declined for each course they signed up for. Maybe also show participation percentage

**Comment by mariusGundersen** [comment]
Show if the user was a member and if they have paid fees for each semester

**Comment by volesi** [comment]
Kan du muligens bytte til invers kronologisk rekkefølge slik at mest relevant år kommer øverst?

Og om mulig ha en accordion type for tidligere semester, slik at ikke alle trenger å vises alltid
