### ISSUE TITLE
Betale medlemskap sammen med arrangement selv om det ikke er påkrevd.

### ISSUE THREAD

**Issue by volesi** [bardarswingclub/MemberService#85]
Under Bårdar Swing Club Revival er det flere som melder seg på som betaler for kurs for første gang for i år. De er da ikke medlemmer i det de skal til å betale. Siden det ikke er krav om medlemskap har de ikke mulighet til å betale medlemskap samtidig som de betaler for arrangementet. De må da finne veien til påmeldingssidene, trykke på "jeg vil ikke ta kurs, bare bli medlem", betale for medlemskap og så dra tilbake å betale for arrangementet. 

## Mål
La det være to alternativer når man betaler der det er prisforskjell på medlem/ikke-medlem, men hvor medlemskap ikke er påkrevd. Noe a la: betal for medlemskap og arrangement kr xxx,-, betal for arrangement kr xxx,- 

Eventuelt enda mer kompliserte ting om kurs eller treningsavgift gjør arrangementet billigere.

**Comment by mariusGundersen** [comment]
Det burde også stå pris på arrangementet før det åpner, og om det krever medlemskap å delta på kurset.
