### ISSUE TITLE
When sending email it should be very clear who it will be from

### ISSUE THREAD

**Issue by mariusGundersen** [bardarswingclub/MemberService#86]
It's not so easy to see who the sender will be in the form for sending emails. It could be made clearer

**Comment by mariusGundersen** [comment]
ReplyTo should be set to the current user by default

**Comment by volesi** [comment]
Blir det sendt kopi til en sentral bårdarkonto uansett? Ikke ønskelig at noen kan sende mailer fra bårdarsiden uten at det er sporbart.

**Comment by mariusGundersen** [comment]
Nei, det gjør det ikke. Mye mulig det skulle vært lagra et sted
